project:
  type: book
  # change output-dir to "docs" to publish to gh pages
  output-dir: docs

book:
  title: "Basic Soil Science (SOIL 2125) Syllabus - Spring 2025"
  author: "Nic Jelinski, Andrea Elvir Flores, and Nora Pearson"
  date: "21JAN2025"
  cover-image: "soil-2125-03.png"
  number: "2.2"
  #navbar: 
    #right: 
      #- icon: cc-circle
      #- href: https://creativecommons.org/licenses/by/4.0/
      #- aria-label: Creative Commons
  
  chapters:
    - index.qmd
    - intro.qmd
    - course-resources.qmd
    - assignments-points-grades.qmd
    - poll-everywhere.qmd
    - makeup-policies.qmd
    - fine-print.qmd
    - class-schedule.qmd
    - further-opportunities.qmd
    # - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

