# Class Schedule - Subject to Change

```{r}
library(knitr)
library(kableExtra)
class.schedule = read.csv("class-schedule.csv")
kable(class.schedule) %>%
  kable_paper("striped", full_width = F) %>%
  column_spec(1, bold = T) %>%
  collapse_rows(columns = 1, valign = "top")
```

```{r}
library(knitr)
library(dplyr)
library(kableExtra)
class.schedule = read.csv("class-schedule.csv")
class.schedule = select(class.schedule, -1)
colnames(class.schedule) = c("Day", "Date", "Topic Focus", "Suggested Readings - Brady and Weil 4th ed", "Lab Unit")

kbl(class.schedule, format = "html") %>%
kable_styling("bordered", full_width = F, fixed_thead = T, html_font = "arial") %>%
  pack_rows("Week 1", 1,3, background = "grey80") %>%
  pack_rows("Week 2", 4,7, color = "grey80") %>%
  pack_rows("Week 3", 8,11) %>%
  pack_rows("Week 4", 12,15) %>%
  pack_rows("Week 5", 16,20) %>%
  pack_rows("Week 6", 21,24) %>%
  pack_rows("Week 7", 25,28) %>%
  pack_rows("Week 8", 29,29) %>%
  pack_rows("Week 9", 30,33) %>%
  pack_rows("Week 10", 34,38) %>%
  pack_rows("Week 11", 39,42) %>%
  pack_rows("Week 12", 43,46) %>%
  pack_rows("Week 13", 47,51) %>%
  pack_rows("Week 14", 52,55) %>%
  pack_rows("Week 15", 56,59) %>%
  pack_rows("Week 16", 60,62) %>%
  scroll_box(width = "100%", height = "1000px")
```

```{r}
library(knitr)
library(dplyr)
library(kableExtra)
class.schedule = read.csv("class-schedule.csv")
class.schedule = select(class.schedule, -1)

kbl(class.schedule) %>%
kable_styling("striped", full_width = F, fixed_thead = T) %>%
  pack_rows("Week 1", 1,3) %>%
  pack_rows("Week 2", 4,7) %>%
  pack_rows("Week 3", 8,11) %>%
  pack_rows("Week 4", 12,15) %>%
  pack_rows("Week 5", 16,19) %>%
  pack_rows("Week 6", 20,23) %>%
  pack_rows("Week 7", 24,27) %>%
  pack_rows("Week 8", 28,28) %>%
  pack_rows("Week 9", 29,32) %>%
  pack_rows("Week 10", 33,36) %>%
  pack_rows("Week 11", 37,40) %>%
  pack_rows("Week 12", 41,44) %>%
  pack_rows("Week 13", 45,48) %>%
  pack_rows("Week 14", 49,52) %>%
  pack_rows("Week 15", 53,56) %>%
  pack_rows("Week 16", 57,59)
```

```{r}
library(knitr)
library(dplyr)
library(kableExtra)
class.schedule = read.csv("class-schedule.csv")
#class.schedule = select(class.schedule, -1)

kbl(class.schedule) %>%
kable_styling("striped", full_width = F, fixed_thead = T) %>%
  column_spec(1, bold = T) %>%
  collapse_rows(columns = 1:2, valign = "top")
```

```{r}
library(htmlTable)
library(dplyr)
class.schedule = read.csv("class-schedule.csv")

class.schedule %>% 
select(-1) %>%
addHtmlTableStyle(col.rgroup = c("none", "#F7F7F7")) %>%
htmlTable(rgroup = c(paste("Week", 1:16)),
          n.rgroup = c(3,4,4,4,4,4,4,1,4,4,4,4,4,4,4),
          tspanner = paste("Week", 1:16),
          n.tspanner = c(3,4,4,4,4,4,4,1,4,4,4,4,4,4,4))
```

| **Week** | **Day** | **Date** | **Topic Focus**                                       | **Suggested Readings**\Brady and Weil 4th Ed. | **Lab Unit** |
|------------|------------|------------|------------|------------|------------|
| 01       | M       | 1/18     | Introduction and Overview, Soil Diversity (1-1)       | pp 3-14                                       | No Lab       |
|          | W       | 1/19     | Soil Physical Properties - Components & Texture (1-2) | pp 15-21                                      |              |
|          | Th      | 1/20     | *Week 1 Discussion*                                   |                                               |              |
|          | F       | 1/21     | \*Weekly Quiz Part II Due \@ 11:59PM (Canvas)         |                                               |              |
|          |         |          |                                                       |                                               |              |
|          |         |          |                                                       |                                               |              |
|          |         |          |                                                       |                                               |              |
|          |         |          |                                                       |                                               |              |
